version: "2"
services:

  eureka-server:
    image: eureka-server
    build: eureka-server/
    container_name: eureka-server
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8761:8761


  api-gateway:
    build: api-gateway/
    container_name: api-gateway
    depends_on:
      - eureka-server
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8080:8080


  authentication-service:
    image: user-authentication-service
    build: user-authentication-service/
    container_name: user-authentication-service
    network_mode: "host"
    hostname: localhost
    ports:
      - 8095:8095
    depends_on:
      - mysql
      - rabbitmq
      - eureka-server

  mysql:
    container_name: "mysql-user"
    image: mysql
    hostname: localhost
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=auth2
      - MYSQL_PASSWORD=root

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 15672:15672
      - 5672:5672


  product-webapp:
    build: product-webapp/
    image: product-webapp
    depends_on:
      - eureka-server
      - api-gateway
    restart: always
    container_name: product-webapp
    network_mode: "host"
    hostname: localhost
    ports:
      - 4200:4200

#
#  skill-service:
#    build: skill-service/
#    image: skill-service
#    depends_on:
#      - eureka-server
#      - api-gateway
#      - rabbitmq
#    restart: always
#    container_name: skill-service
#    network_mode: "host"
#    hostname: localhost
#    ports:
#      - 8088:8088

#  academics-service:
#    build: academics-service/
#    image: academics-service
#    depends_on:
#      - eureka-server
#      - api-gateway
#      - rabbitmq
#    restart: always
#    container_name: academics-service
##    network_mode: "host"
#    hostname: localhost
#    ports:
#      - 8082:8082

#  experience-service:
#    build: experience-service/
#    image: experience-service
#    depends_on:
#      - eureka-server
#      - api-gateway
#      - rabbitmq
#    restart: always
#    container_name: experience-service
##    network_mode: "host"
#    hostname: localhost
#    ports:
#      - 8084:8084
#
#  personal-detail-service:
#    build: personal-detail-service/
#    image: personal-detail-service
#    depends_on:
#      - eureka-server
#      - api-gateway
#      - rabbitmq
#    restart: always
#    container_name: personal-detail-service
##    network_mode: "host"
#    hostname: localhost
#    ports:
#      - 8083:8083
#
#  profile-service:
#    build: profile-service/
#    image: profile-service
#    depends_on:
#      - eureka-server
#      - api-gateway
#      - neo4j
#      - rabbitmq
#    restart: always
#    container_name: profile-service
##    network_mode: "host"
#    hostname: localhost
#    ports:
#      - 8090:8090
#
#  email-service:
#    build: email-service/
#    image: email-service
#    depends_on:
#      - eureka-server
#      - api-gateway
#      - rabbitmq
#    restart: always
#    container_name: email-service
##   network_mode: "host"
#    hostname: localhost
#    ports:
#      - 8888:8888
#
  neo4j:
    image: neo4j:4.2.3
    container_name: neo4j
    restart: always
    network_mode: "host"
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/admin
      NEO4J_dbms_default__database: job4u

